kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv-volume
  labels:
    type: local
    app: theshow-database
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim
  labels:
    app: theshow-database
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: theshow-database
spec:
  selector:
    matchLabels:
      app: theshow-database
  replicas: 1
  template:
    metadata:
      labels:
        app: theshow-database
    spec:
      containers:
        - name: theshow-database
          image: postgres:latest
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
          env:
            - name: POSTGRES_PASSWORD
              value: testpassword
            - name: PGDATA
              value: /data/pgdata
      volumes:
      - name: postgredb
        persistentVolumeClaim:
          claimName: postgres-pv-claim