apiVersion: v1
kind: Service
metadata:
  name: theshow-core
spec:
  type: NodePort
  selector:
    app: theshow-core
  ports:
  - port: 5001
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: theshow-identity
spec:
  type: NodePort
  selector:
    app: theshow-identity
  ports:
  - port: 5003
    targetPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: theshow-react
spec:
  type: NodePort
  selector:
    app: theshow-react
  ports:
  - port: 5002
    targetPort: 80